In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('C:/Users/Dell/Desktop/pythonDS/pythonfordsagain/Retail_Data_cleaning_n_analysis/Retail-Data-Analysis/Cleaned_Retail_Store_sales.csv')

In [5]:
df.shape

(11971, 10)

In [6]:
df.describe(include = 'all')

,Transaction_ID,Customer_ID,Category,Item,Price_Per_Unit,Quantity,Total_Spent,Payment_Method,Location,Transaction_Date
count,11971,11971,11971,11971,11971.000000,11971.000000,11971.000000,11971,11971,11971
unique,11971,25,8,201,NaN,NaN,NaN,3,2,1114
top,TXN_2407494,CUST_24,Furniture,Unknown_Item,NaN,NaN,NaN,Cash,Online,2022-05-30
freq,1,519,1525,609,NaN,NaN,NaN,4103,6068,26
mean,NaN,NaN,NaN,NaN,23.360872,5.536380,129.652577,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,10.741889,2.857883,94.750697,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,5.000000,1.000000,5.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,14.000000,3.000000,51.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,23.000000,6.000000,108.500000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,33.500000,8.000000,192.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,41.000000,10.000000,410.000000,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11971 entries, 0 to 11970
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    11971 non-null  object
 1   Customer_ID       11971 non-null  object
 2   Category          11971 non-null  object
 3   Item              11971 non-null  object
 4   Price_Per_Unit    11971 non-null  float64
 5   Quantity          11971 non-null  int64
 6   Total_Spent       11971 non-null  float64
 7   Payment_Method    11971 non-null  object
 8   Location          11971 non-null  object
 9   Transaction_Date  11971 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 935.4+ KB

In [10]:
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])

In [11]:
#Creating a month Column to check when do customers spend the most

df['Month'] = df['Transaction_Date'].dt.month

In [12]:
df.head()

,Transaction_ID,Customer_ID,Category,Item,Price_Per_Unit,Quantity,Total_Spent,Payment_Method,Location,Transaction_Date,Month
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,4
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,7
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,10
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07,5
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02,10

In [15]:
#Now we Will DO EDA on the Dateset we cleaned
# 1 Which category generates the most revenue

df.groupby('Category')['Total_Spent'].sum().sort_values(ascending = False).reset_index()

                             Category  Total_Spent
0                            Butchers     208118.0
1       Electric household essentials     203813.5
2                           Beverages     197047.5
3                           Furniture     195310.0
4                                Food     194812.0
5  Computers and electric accessories     190692.5
6                          Patisserie     182165.5
7                       Milk Products     180112.0

In [36]:
# 2 Which payment method is used the most?

df.groupby('Payment_Method')['Transaction_ID'].count().reset_index()

   Payment_Method  Transaction_ID
0            Cash            4103
1     Credit Card            3927
2  Digital Wallet            3941

In [39]:
# 2 Which payment method is used the most?its same mostly professionals use this method
df["Payment_Method"].value_counts().reset_index()

   Payment_Method  count
0            Cash   4103
1  Digital Wallet   3941
2     Credit Card   3927

In [26]:
# 3 Whether online or physical store generates more revenue.

df.groupby('Location')['Total_Spent'].sum().sort_values(ascending = False).reset_index()

   Location  Total_Spent
0    Online     791401.0
1  In-store     760670.0

In [32]:
# 4 Identify high-value customers.

df.groupby('Customer_ID')['Total_Spent'].sum().sort_values(ascending = False).reset_index().head()

  Customer_ID  Total_Spent
0     CUST_24      68452.0
1     CUST_08      67351.5
2     CUST_05      66974.5
3     CUST_16      65570.5
4     CUST_13      65037.0

In [41]:
# 6 Which category sells the most items (not revenue)?

df.groupby('Category')['Quantity'].sum().sort_values(ascending = False).reset_index()

                             Category  Quantity
0                           Furniture      8462
1                                Food      8387
2                           Beverages      8358
3                       Milk Products      8339
4       Electric household essentials      8309
5  Computers and electric accessories      8272
6                            Butchers      8206
7                          Patisserie      7943

In [34]:
# 5 Monthly Sales Trend

df.groupby('Month')['Total_Spent'].sum().sort_values(ascending = False).reset_index().head()

   Month  Total_Spent
0      1     174421.0
1      7     131509.0
2      6     129771.0
3     12     129688.5
4      9     129344.0