In [2]:
import requests
import pandas as pd

In [3]:
url = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd"

response = requests.get(url)
data = response.json()

In [4]:
type(data)

list

In [5]:
data[:5]

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 70151,
  'market_cap': 1403762090921,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1403762582205,
  'total_volume': 43312218928,
  'high_24h': 70801,
  'low_24h': 69265,
  'price_change_24h': -336.939848515045,
  'price_change_percentage_24h': -0.47801,
  'market_cap_change_24h': -6829989644.39502,
  'market_cap_change_percentage_24h': -0.48419,
  'circulating_supply': 20001321.0,
  'total_supply': 20001328.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -44.35961,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 67.81,
  'atl_change_percentage': 103354.32148,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T20:43:44.405Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 2061.05,
  'market_cap': 248851846990,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 248851846990,
  'total_volume': 18293551903,
  'high_24h': 2080.91,
  'low_24h': 2020.71,
  'price_change_24h': -9.376695533971088,
  'price_change_percentage_24h': -0.45289,
  'market_cap_change_24h': -1033799809.7038574,
  'market_cap_change_percentage_24h': -0.41371,
  'circulating_supply': 120691977.447831,
  'total_supply': 120691977.447831,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -58.32929,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 0.432979,
  'atl_change_percentage': 475917.11315,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 38.25442689935118,
   'currency': 'btc',
   'percentage': 3825.442689935118},
  'last_updated': '2026-03-12T20:43:53.539Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 0.999982,
  'market_cap': 183957375040,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 189424237627,
  'total_volume': 67617908818,
  'high_24h': 1.0,
  'low_24h': 0.999899,
  'price_change_24h': -6.7639582757795e-05,
  'price_change_percentage_24h': -0.00676,
  'market_cap_change_24h': 54738716,
  'market_cap_change_percentage_24h': 0.02977,
  'circulating_supply': 183959901909.3361,
  'total_supply': 189426839589.9362,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.41987,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.66558,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T20:43:54.105Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 649.41,
  'market_cap': 88557237882,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 88557237232,
  'total_volume': 862818522,
  'high_24h': 657.13,
  'low_24h': 642.38,
  'price_change_24h': -3.1128302079026753,
  'price_change_percentage_24h': -0.47705,
  'market_cap_change_24h': -386184912.4086609,
  'market_cap_change_percentage_24h': -0.43419,
  'circulating_supply': 136358175.34,
  'total_supply': 136358174.34,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -52.59767,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1630853.13594,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T20:43:51.654Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.37,
  'market_cap': 84085622335,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 137312715813,
  'total_volume': 1930367065,
  'high_24h': 1.39,
  'low_24h': 1.37,
  'price_change_24h': -0.018386030749176774,
  'price_change_percentage_24h': -1.32128,
  'market_cap_change_24h': -1095036933.263794,
  'market_cap_change_percentage_24h': -1.28555,
  'circulating_supply': 61227832454.0,
  'total_supply': 99985701766.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -62.34215,
  'ath_date': '2025-07-18T03:40:53.808Z',
  'atl': 0.00268621,
  'atl_change_percentage': 51018.46801,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T20:43:44.943Z'}]

In [47]:
df.shape

(100, 26)

In [88]:
df = pd.DataFrame(data)
df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                100 non-null    object
 1   symbol                            100 non-null    object
 2   name                              100 non-null    object
 3   image                             100 non-null    object
 4   current_price                     100 non-null    float64
 5   market_cap                        100 non-null    int64
 6   market_cap_rank                   100 non-null    int64
 7   fully_diluted_valuation           100 non-null    int64
 8   total_volume                      100 non-null    float64
 9   high_24h                          100 non-null    float64
 10  low_24h                           100 non-null    float64
 11  price_change_24h                  100 non-null    float64
 12  price_change_percentage_24h       100 non-null    float64
 13  market_cap_change_24h             100 non-null    float64
 14  market_cap_change_percentage_24h  100 non-null    float64
 15  circulating_supply                100 non-null    float64
 16  total_supply                      100 non-null    float64
 17  max_supply                        52 non-null     float64
 18  ath                               100 non-null    float64
 19  ath_change_percentage             100 non-null    float64
 20  ath_date                          100 non-null    object
 21  atl                               100 non-null    float64
 22  atl_change_percentage             100 non-null    float64
 23  atl_date                          100 non-null    object
 24  roi                               11 non-null     object
 25  last_updated                      100 non-null    object
dtypes: float64(15), int64(3), object(8)
memory usage: 20.4+ KB

In [49]:
df = df[['name', 
         'symbol', 
         'current_price', 
         'market_cap', 
         'market_cap_rank', 
         'total_volume', 
         'price_change_percentage_24h', 
         'circulating_supply', 
         'ath',
         'atl'
        ]]

In [52]:
df.to_csv('updated_coungekco_dataset_for_analysis.csv', index = False)

In [53]:
#creating Columns

df['price_distance_from_ath'] = df['ath'] - df['current_price']

In [55]:
df['price_distance_from_atl'] = df['current_price'] - df['atl']

In [56]:
df['volatility_estimate'] = df['ath'] - df['atl']

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         100 non-null    object
 1   symbol                       100 non-null    object
 2   current_price                100 non-null    float64
 3   market_cap                   100 non-null    int64
 4   market_cap_rank              100 non-null    int64
 5   total_volume                 100 non-null    float64
 6   price_change_percentage_24h  100 non-null    float64
 7   circulating_supply           100 non-null    float64
 8   ath                          100 non-null    float64
 9   atl                          100 non-null    float64
 10  price_distance_from_ath      100 non-null    float64
 11  price_distance_from_atl      100 non-null    float64
 12  volatility_estimate          100 non-null    float64
dtypes: float64(9), int64(2), object(2)
memory usage: 10.3+ KB

In [58]:
df.to_csv('crypto_market_data_v3.csv', index = False)

In [69]:
df.head()

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,ath,atl,price_distance_from_ath,price_distance_from_atl,volatility_estimate
0,Bitcoin,btc,70151.000000,1403762090921,1,4.331222e+10,-0.47801,2.000132e+07,126080.00,67.810000,55929.000000,70083.190000,126012.190000
1,Ethereum,eth,2061.050000,248851846990,2,1.829355e+10,-0.45289,1.206920e+08,4946.05,0.432979,2885.000000,2060.617021,4945.617021
2,Tether,usdt,0.999982,183957375040,3,6.761791e+10,-0.00676,1.839599e+11,1.32,0.572521,0.320018,0.427461,0.747479
3,BNB,bnb,649.410000,88557237882,4,8.628185e+08,-0.47705,1.363582e+08,1369.99,0.039818,720.580000,649.370182,1369.950182
4,XRP,xrp,1.370000,84085622335,5,1.930367e+09,-1.32128,6.122783e+10,3.65,0.002686,2.280000,1.367314,3.647314

In [60]:
#Top 10 Crypto

df.sort_values('market_cap',ascending = False).head(10)

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,ath,atl,price_distance_from_ath,price_distance_from_atl,volatility_estimate
0,Bitcoin,btc,70151.000000,1403762090921,1,4.331222e+10,-0.47801,2.000132e+07,126080.000000,67.810000,55929.000000,70083.190000,126012.190000
1,Ethereum,eth,2061.050000,248851846990,2,1.829355e+10,-0.45289,1.206920e+08,4946.050000,0.432979,2885.000000,2060.617021,4945.617021
2,Tether,usdt,0.999982,183957375040,3,6.761791e+10,-0.00676,1.839599e+11,1.320000,0.572521,0.320018,0.427461,0.747479
3,BNB,bnb,649.410000,88557237882,4,8.628185e+08,-0.47705,1.363582e+08,1369.990000,0.039818,720.580000,649.370182,1369.950182
4,XRP,xrp,1.370000,84085622335,5,1.930367e+09,-1.32128,6.122783e+10,3.650000,0.002686,2.280000,1.367314,3.647314
5,USDC,usdc,0.999910,78799483013,6,7.323366e+09,-0.00347,7.880477e+10,1.043000,0.877647,0.043090,0.122263,0.165353
6,Solana,sol,86.510000,49413952247,7,3.697924e+09,-0.80037,5.711128e+08,293.310000,0.500801,206.800000,86.009199,292.809199
7,TRON,trx,0.288858,27367375686,8,3.783597e+08,-0.76079,9.474671e+10,0.431288,0.001804,0.142430,0.287054,0.429484
8,Figure Heloc,figr_heloc,1.033000,16316480089,9,1.655747e+07,-0.12248,1.579596e+10,1.049000,0.155357,0.016000,0.877643,0.893643
9,Dogecoin,doge,0.094235,14452507748,10,1.044342e+09,0.76964,1.533799e+11,0.731578,0.000087,0.637343,0.094148,0.731491

In [62]:
# Highest Trading Volume Coins

df.sort_values('total_volume', ascending = False).head(10)

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,ath,atl,price_distance_from_ath,price_distance_from_atl,volatility_estimate
2,Tether,usdt,0.999982,183957375040,3,6.761791e+10,-0.00676,1.839599e+11,1.320000,0.572521,0.320018,0.427461,0.747479
0,Bitcoin,btc,70151.000000,1403762090921,1,4.331222e+10,-0.47801,2.000132e+07,126080.000000,67.810000,55929.000000,70083.190000,126012.190000
1,Ethereum,eth,2061.050000,248851846990,2,1.829355e+10,-0.45289,1.206920e+08,4946.050000,0.432979,2885.000000,2060.617021,4945.617021
5,USDC,usdc,0.999910,78799483013,6,7.323366e+09,-0.00347,7.880477e+10,1.043000,0.877647,0.043090,0.122263,0.165353
6,Solana,sol,86.510000,49413952247,7,3.697924e+09,-0.80037,5.711128e+08,293.310000,0.500801,206.800000,86.009199,292.809199
4,XRP,xrp,1.370000,84085622335,5,1.930367e+09,-1.32128,6.122783e+10,3.650000,0.002686,2.280000,1.367314,3.647314
21,USD1,usd1,0.999536,4613577374,22,1.323952e+09,-0.02615,4.616424e+09,1.025000,0.989633,0.025464,0.009903,0.035367
9,Dogecoin,doge,0.094235,14452507748,10,1.044342e+09,0.76964,1.533799e+11,0.731578,0.000087,0.637343,0.094148,0.731491
3,BNB,bnb,649.410000,88557237882,4,8.628185e+08,-0.47705,1.363582e+08,1369.990000,0.039818,720.580000,649.370182,1369.950182
28,Sui,sui,0.973521,3797276251,29,4.377510e+08,-0.94151,3.899985e+09,5.350000,0.364846,4.376479,0.608675,4.985154

In [63]:
# Biggest 24h Gainers

df.sort_values('price_change_percentage_24h', ascending = False).head(10)

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,ath,atl,price_distance_from_ath,price_distance_from_atl,volatility_estimate
38,Pi Network,pi,0.257211,2485247814,39,102783666.0,9.13359,9.662292e+09,2.990000,0.131244,2.732789,0.125967,2.858756
42,Bittensor,tao,213.470000,2049345952,43,180285717.0,6.24967,9.597491e+06,757.600000,30.830000,544.130000,182.640000,726.770000
72,Render,render,1.630000,844754355,73,78150774.0,6.08712,5.187433e+08,13.530000,0.036657,11.900000,1.593343,13.493343
84,XDC Network,xdc,0.033158,661126802,85,15965309.0,3.12070,1.993732e+10,0.192754,0.000395,0.159596,0.032763,0.192359
49,NEAR Protocol,near,1.330000,1716652438,50,226151422.0,3.10526,1.290004e+09,20.440000,0.526762,19.110000,0.803238,19.913238
35,MemeCore,m,1.470000,2563846960,36,8488913.0,2.99362,1.745321e+09,2.960000,0.047461,1.490000,1.422539,2.912539
14,Hyperliquid,hype,36.970000,8811215461,15,377433540.0,2.92155,2.383853e+08,59.300000,3.810000,22.330000,33.160000,55.490000
40,Mantle,mnt,0.713999,2342574266,41,34976173.0,2.78057,3.277944e+09,2.860000,0.307978,2.146001,0.406021,2.552022
60,Pump.fun,pump,0.002074,1222341293,61,99254029.0,2.43603,5.900000e+11,0.008819,0.001684,0.006745,0.000389,0.007135
45,Sky,sky,0.081411,1876543328,46,17985500.0,2.35606,2.304831e+10,0.100535,0.035827,0.019124,0.045584,0.064708

In [66]:
# Coins closest to their All-Time High.

df.sort_values('price_distance_from_ath').head(5)

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,ath,atl,price_distance_from_ath,price_distance_from_atl,volatility_estimate
41,Circle USYC,usyc,1.120,2310883935,42,99.62,-0.00022,2.064593e+09,1.120,1.026,0.0,0.094,0.094
62,Superstate Short Duration U.S. Government Secu...,ustb,11.020,1091149443,63,0.00,0.00961,9.904165e+07,11.020,10.290,0.0,0.730,0.730
43,BlackRock USD Institutional Digital Liquidity ...,buidl,1.000,1993947246,44,0.00,0.00000,1.993947e+09,1.000,1.000,0.0,0.000,0.000
83,Janus Henderson Anemoy Treasury Fund,jtrsy,1.097,668598023,84,0.00,0.00848,6.094925e+08,1.097,1.085,0.0,0.012,0.012
80,OUSG,ousg,114.570,723382418,81,0.00,0.00926,6.314046e+06,114.570,95.090,0.0,19.480,19.480

In [67]:
# Most volatile coins:

df.sort_values('volatility_estimate', ascending = False).head(10)

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,ath,atl,price_distance_from_ath,price_distance_from_atl,volatility_estimate
0,Bitcoin,btc,70151.00,1403762090921,1,4.331222e+10,-0.47801,2.000132e+07,126080.00,67.810000,55929.00,70083.190000,126012.190000
1,Ethereum,eth,2061.05,248851846990,2,1.829355e+10,-0.45289,1.206920e+08,4946.05,0.432979,2885.00,2060.617021,4945.617021
36,PAX Gold,paxg,5081.78,2540100684,37,2.769950e+08,-1.85327,4.999613e+05,5619.09,1399.640000,537.31,3682.140000,4219.450000
33,Tether Gold,xaut,5048.23,2849515655,34,3.206457e+08,-1.71613,5.645486e+05,5504.62,1447.840000,456.39,3600.390000,4056.780000
13,Bitcoin Cash,bch,454.04,9083202654,14,1.701994e+08,-0.61585,2.000645e+07,3785.82,76.930000,3331.78,377.110000,3708.890000
30,Zcash,zec,207.54,3445525725,31,2.577555e+08,-2.45835,1.659894e+07,3191.93,16.080000,2984.39,191.460000,3175.850000
3,BNB,bnb,649.41,88557237882,4,8.628185e+08,-0.47705,1.363582e+08,1369.99,0.039818,720.58,649.370182,1369.950182
16,Monero,xmr,351.59,6487946702,17,7.905780e+07,-1.15360,1.844674e+07,797.73,0.216177,446.14,351.373823,797.513823
42,Bittensor,tao,213.47,2049345952,43,1.802857e+08,6.24967,9.597491e+06,757.60,30.830000,544.13,182.640000,726.770000
54,Internet Computer,icp,2.64,1451682191,55,1.031246e+08,-0.88953,5.494568e+08,700.65,2.020000,698.01,0.620000,698.630000